In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [5]:
np.save('my_array', arr)

In [6]:
arr = np.arange(10)

In [7]:
array

NameError: name 'array' is not defined

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [10]:
arr1 = np.load('my_array.npy')

In [11]:
arr1

array([0, 1, 2, 3, 4])

In [12]:
arr2 = np.arange(10)

In [13]:
arr1

array([0, 1, 2, 3, 4])

In [14]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.savez('ziparray.npz', x=arr1, y=arr2)

In [20]:
archive_array = np.load('ziparray.npz')

In [23]:
archive_array

In [24]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [27]:
arr = np.array([[1,2,3,4], [4,5,6,7]])

In [28]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [29]:
np.savetxt('my_test.txt', arr, delimiter=',')

In [32]:
!cat my_test.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00


In [35]:
arr

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.]])

In [36]:
arr = np.loadtxt('my_test.txt', delimiter=',')

In [37]:
arr

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.]])