In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0, 1, 2], index=['T', 'U', 'V'])
ser2 = Series([3,4], index=['x', 'y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

x    3
y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2, ser1])

T    0
U    1
V    2
x    3
y    4
T    0
U    1
V    2
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
x  NaN  3.0
y  NaN  4.0

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  x    3
      y    4
dtype: int64

In [14]:
pd.concat([ser1, ser2], axis=1, keys=['cat1', 'cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
x   NaN   3.0
y   NaN   4.0

In [16]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['x', 'y', 'z'])

In [17]:
dframe1

x         y         z
0  1.094969  0.868334 -0.750953
1  0.973396  0.252039 -0.859155
2  0.182714  0.335849  0.232642
3  0.017649  1.435437 -0.902275

In [21]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'x'])

In [22]:
dframe2

Y         Q         x
0 -1.231006  0.765172 -0.351934
1 -0.810394 -0.541653 -0.885438
2  0.743901 -0.700897  1.069769

In [23]:
pd.concat([dframe1, dframe2])

Q         Y         x         y         z
0       NaN       NaN  1.094969  0.868334 -0.750953
1       NaN       NaN  0.973396  0.252039 -0.859155
2       NaN       NaN  0.182714  0.335849  0.232642
3       NaN       NaN  0.017649  1.435437 -0.902275
0  0.765172 -1.231006 -0.351934       NaN       NaN
1 -0.541653 -0.810394 -0.885438       NaN       NaN
2 -0.700897  0.743901  1.069769       NaN       NaN

In [24]:
pd.concat([dframe1, dframe2], ignore_index=True)

Q         Y         x         y         z
0       NaN       NaN  1.094969  0.868334 -0.750953
1       NaN       NaN  0.973396  0.252039 -0.859155
2       NaN       NaN  0.182714  0.335849  0.232642
3       NaN       NaN  0.017649  1.435437 -0.902275
4  0.765172 -1.231006 -0.351934       NaN       NaN
5 -0.541653 -0.810394 -0.885438       NaN       NaN
6 -0.700897  0.743901  1.069769       NaN       NaN