In [1]:
Import numpy as np

SyntaxError: invalid syntax (<ipython-input-1-385435a876ae>, line 1)

In [2]:
import numpy as np

In [3]:
5/2

2.5

In [4]:
from __furure__ import devision

ImportError: No module named '__furure__'

In [5]:
from __future__ import devision

SyntaxError: future feature devision is not defined (<ipython-input-5-fa7ce90f8912>, line 1)

In [6]:
from __future__ import division

In [7]:
arr1 = np.array([1,2,3,4], [8,9,10,11])

TypeError: data type not understood

In [8]:
arr1 = np.array[([1,2,3,4], [8,9,10,11]])

SyntaxError: invalid syntax (<ipython-input-8-abd6a6094153>, line 1)

In [9]:
arr1 = np.array([[1,2,3,4], [8,9,10,11]])

In [10]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [11]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [12]:
arr1-arra1


NameError: name 'arra1' is not defined

In [13]:
arr1-arr1


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [15]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])